window.lyrics = [
  'This is ground control to Major Tom You'/'ve really made the grade',
  'Man is an obstacle, sad as the clown, Oh by jingo So hold on to nothing, and he wont let you down, Oh jingo',
  'It'/'s been a hard days night, and I'/'ve been working like a dog',
  'Imagine there is no Heaven',
  'Purple Haze all around, don'/'t know if I'/'m coming down',
  'Is you is or is you ain'/'t my baby',
  'I'/'m just a gigolo, everywhere I go People know the part I'/'m playing Paid for every dance Starting each romance Oh, what their saying',
  'I am the passenger And I ride and I ride I ride through the city'/'s backside I see the stars come out of the sky',
  'Now so long, Marianne, it'/'s time that we began to laugh and cry and cry and laugh about it all again. ',
  'It goes like this The fourth, the fifth The minor fall, the major lift The baffled king composing Hallelujah',
  'How does it feel To be without a home Like a complete unknown Like a rolling stone ?',
  'Lets get hot on the dancing spot, oh is it hot? Then let'/'s get cool in the pool,',
  'I'/'ve been working from seven to eleven every night, I said It kinda makes my life a drag Lord, that aint right',
  'Whiskey and wimmen almost wrecked my life Were'/'nt for whiskey and wimmin, I'/'d have money today',
  'Well Im not dumb but I cant understand Why she walk like a woman and talk like a man Oh my Lola, lo lo lo lo Lola, lo lo lo lo Lola',
  'Whiskey and wimmen almost wrecked my life Were'/'nt for whiskey and wimmin, I'/'d have money today',
  'Always look on the bright side of life If life seems jolly rotten, There'/'s something you'/'ve forgotten!',
  'I woke up with my feet nailed down And my head moving the speed of sound'
];
